# Generated by Django 3.1.6 on 2021-04-14 18:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('create_date', models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 14, 18, 39, 48, 162874))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ToDoListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('create_date', models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 14, 18, 39, 48, 164264))),
                ('deadline', models.DateTimeField()),
                ('status', models.TextField(choices=[('UNCOMPLETED', 'Uncompleted'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired')])),
                ('todolist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.todolist')),
            ],
        ),
    ]
