# Generated by Django 3.1.6 on 2021-04-17 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210414_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 17, 16, 15, 54, 565661)),
        ),
        migrations.AlterField(
            model_name='todolistitem',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 17, 16, 15, 54, 567049)),
        ),
    ]
