# Generated by Django 3.1.6 on 2021-04-17 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20210417_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 17, 14, 33, 25, 495053)),
        ),
        migrations.AlterField(
            model_name='todolistitem',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 17, 14, 33, 25, 495767)),
        ),
    ]
