# Generated by Django 3.1.6 on 2021-04-18 07:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20210417_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 18, 7, 20, 17, 17428)),
        ),
        migrations.AlterField(
            model_name='todolistitem',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 18, 7, 20, 17, 18910)),
        ),
    ]
