# Generated by Django 3.1.6 on 2021-04-18 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_auto_20210418_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 18, 13, 43, 33, 874060)),
        ),
        migrations.AlterField(
            model_name='todolistitem',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 18, 13, 43, 33, 875640)),
        ),
        migrations.AlterField(
            model_name='todolistitem',
            name='status',
            field=models.TextField(choices=[('UNCOMPLETED', 'Uncompleted'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired')], default='UNCOMPLETED'),
        ),
    ]
